# Site settings
title: 大蜕
email: changhbaga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  认识自己,放下自己.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://homuralovelive.com" # the base hostname & protocol for your site
twitter_username: sddtc_
github_username:  sddtc

# Build settings
markdown: kramdown
