markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
url: https://homuralovelive.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
name: "大蜕-个人博客"
title: "大蜕-个人博客"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: /film.html
  - title: Comments Board
    class: fa fa-comments
    href: /comments.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

# Theme customization - please change from the defaults!
theme_settings:
  # Color for top bar, links, etc
  highlight_color: '#0F0'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: sddtc
    twitter: sddtc_

  # "Hi, I'm _______"
  name: 大蜕
  email: changhbaga@gmail.com
  tagline: "sddtc"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-46032200-2
  google_analytics_domain: homuralovelive.com
  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
